# Generated by Django 4.2.1 on 2023-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0005_alter_tasks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
