# Generated by Django 4.2.1 on 2023-11-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0006_tasks_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='date',
            new_name='creationDate',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completionDate',
            field=models.DateField(default=None),
        ),
    ]
