# Generated by Django 4.2.1 on 2023-11-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0007_rename_date_tasks_creationdate_tasks_completiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completionDate',
            field=models.DateField(null=True),
        ),
    ]
