# Generated by Django 4.2.1 on 2023-11-15 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0008_alter_tasks_completiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=150)),
                ('logDate', models.DateField(default=datetime.date(2023, 11, 15))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayStatus', to='dayTracker.usermodel')),
            ],
        ),
    ]
