# Generated by Django 4.2.1 on 2023-11-15 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0009_daystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='logDate',
            field=models.DateField(default=datetime.date(2023, 11, 15), unique=True),
        ),
    ]
