# Generated by Django 4.2.1 on 2023-11-16 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0010_alter_daystatus_logdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='logDate',
            field=models.DateField(default=datetime.date(2023, 11, 16)),
        ),
    ]
