# Generated by Django 4.2.1 on 2023-11-24 07:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0011_alter_daystatus_logdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='daystatus',
            name='logDate',
            field=models.DateField(default=datetime.date(2023, 11, 24)),
        ),
    ]
