# Generated by Django 4.2.1 on 2023-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0012_tasks_priority_alter_daystatus_logdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completionDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
