# Generated by Django 4.2.1 on 2023-11-30 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0014_alter_tasks_completiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='logDate',
            field=models.DateField(default=datetime.date(2023, 11, 30)),
        ),
        migrations.CreateModel(
            name='nightMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNightModeOn', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightMode', to='dayTracker.usermodel')),
            ],
        ),
    ]
