# Generated by Django 4.2.1 on 2023-12-02 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayTracker', '0015_alter_daystatus_logdate_nightmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystatus',
            name='logDate',
            field=models.DateField(default=datetime.date(2023, 12, 2)),
        ),
    ]
